/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.app;

import org.apache.commons.math3.fraction.BigFraction;
import org.example.lib.Library;

public class App {
    public String getGreeting() {
        return "Hello world!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        var x = new Library().someFractions();
        System.out.println(x);
    }
}
